#let meta = (
  title: "Equipmentmonitoring mit AAS und EDC",
  author: "Josia Rudolph",
  degree: "Belegarbeit",
  faculty: "Informatik/Mathematik",
  supervisor: "Prof. Dr. Reichelt",
  advisors: ("Stefan Vogt", "Paul Patolla"),
  bibNumber: "s88598",
  MatrikelNumber: "s88598",
  submissionDate: datetime(day: 28, month: 02, year: 2026),
  City: "Dresden",
)

#let acronyms = (
  "TUD": ("Technische Universität Dresden",),
  "API": ("Application Programming Interface", "Application Programming Interfaces"),
  "CGSA": ("Computer Graphics, Systems and Applications",),
  "AAS": "Asset Administration Shell",
  "ABAC": "Attribute Based Access Control",
  "BaSyx": "Basic-Industrie-4.0-System-Infrastruktur",
  "EDC": "Eclipse Dataspace Connector",
  "HTTP": "Hypertext Transfer Protocol",
  "IESE": "Fraunhofer-Institut für Experimentelles Software Engineering",
  "MLP": "MultiLanguageProperty",
  "Prop": "Property",
  "REST": "Representational State Transfer",
  "Shell": "AdministrationShell",
  "SMC": "SubmodelElementCollection",
  "SML": "SubmodelElementList",
  "Sub": "Submodel",
  "SDK": "Software development kit",
  "GUI": "grafische Benutzeroberfläche",
  "IDTA": "Industrial Digital Twin Association",
  "IDSA": "Iternationnal Data Spaces Association",
  "CSV": "Comma Seperated Value",
  "JSON": "Java Script Object Notation",
  "ERP": "Enterprise Resource Planning",
  "EDR": "Endpoint Data Reference",
)
